name: Update Changelog

on:
  pull_request:
    types: [closed]

jobs:
  update-notes:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Update Release Notes
        uses: geyerandreas/makimono-action@326374b2fabdb4bad2b0f449b1a6b259a48543a8 # v0.1.4
        with:
          release_notes_file: CHANGELOG.md
          start_header: "## Latest Changes"
          label_header_prefix: "### "
          end_regex: (?m)(^## .*)|(^# .*)
